apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r12x0xykt-go
  janus-idp.io/tekton: r12x0xykt-go
  backstage.io/kubernetes-id: r12x0xykt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r12x0xykt-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
